default:
    image: google/cloud-sdk:alpine
    before_script:
        - gcloud auth activate-service-account --key-file $GOOGLE_CLOUD_CREDENTIALS
        - gcloud config set project $GOOGLE_CLOUD_PROJECT

build:
    stage: build
    script:
        - gcloud builds submit --tag gcr.io/$GOOGLE_CLOUD_PROJECT/project2650


deploy:
    stage: deploy
    script:
        - gcloud run deploy project2650 --image gcr.io/$GOOGLE_CLOUD_PROJECT/project2650 --platform managed --region us-west1 --allow-unauthenticated --update-env-vars=MONGODBURI=$MONGODBURI
