test:
    image: node:12-alpine
    stage: test
    script:
        - cd frontend/
        - yarn install
        - yarn test
        - cd ../backend/
        - yarn install
        - yarn test

deploy:
    image: google/cloud-sdk:alpine
    stage: deploy
    script:
        - gcloud config set project $GOOGLE_CLOUD_PROJECT
        - gcloud auth activate-service-account --key-file $GOOGLE_CLOUD_CREDENTIALS
        - gcloud builds submit --tag gcr.io/$GOOGLE_CLOUD_PROJECT/project2650
        - gcloud run deploy project2650 --image gcr.io/$GOOGLE_CLOUD_PROJECT/project2650 --platform managed --region us-west1 --allow-unauthenticated --update-env-vars=MONGODBURI=$MONGODBURI --update-env-vars=GOOGLE_OAUTH_SECRET=$GOOGLE_OAUTH_SECRET --update-env-vars=RECAPTCHA_SECRET=$RECAPTCHA_SECRET --update-env-vars=NODE_ENV=production --memory=1Gi
